(in-package #:%syntex.wfc.sample)

(u:fn-> load ((or pathname string)) grid:grid)
(defun load (file-path)
  (declare (optimize speed))
  (let* ((image (img:make-image file-path))
         (width (img:width image))
         (height (img:height image))
         (data (img:data image))
         (sample (grid:make-grid width height)))
    (grid:do-cells (sample cell)
      (let ((index (+ (* (grid:y cell) width) (grid:x cell))))
        (setf (grid:value cell) (aref data index))))
    sample))
