(in-package #:origin.mat3)

(deftype mat () '(simple-array single-float (9)))

(defmacro with-components (((prefix matrix) &rest rest) &body body)
  (a:once-only (matrix)
    `(symbol-macrolet ((,prefix ,matrix)
                       (,(make-accessor-symbol prefix "00") (aref ,matrix 0))
                       (,(make-accessor-symbol prefix "10") (aref ,matrix 1))
                       (,(make-accessor-symbol prefix "20") (aref ,matrix 2))
                       (,(make-accessor-symbol prefix "01") (aref ,matrix 3))
                       (,(make-accessor-symbol prefix "11") (aref ,matrix 4))
                       (,(make-accessor-symbol prefix "21") (aref ,matrix 5))
                       (,(make-accessor-symbol prefix "02") (aref ,matrix 6))
                       (,(make-accessor-symbol prefix "12") (aref ,matrix 7))
                       (,(make-accessor-symbol prefix "22") (aref ,matrix 8)))
       ,(if rest
            `(with-components ,rest ,@body)
            `(progn ,@body)))))

(defmacro with-elements (((prefix m00 m01 m02 m10 m11 m12 m20 m21 m22)
                          &rest rest)
                         &body body)
  (let ((%m00 (make-accessor-symbol prefix "00"))
        (%m01 (make-accessor-symbol prefix "01"))
        (%m02 (make-accessor-symbol prefix "02"))
        (%m10 (make-accessor-symbol prefix "10"))
        (%m11 (make-accessor-symbol prefix "11"))
        (%m12 (make-accessor-symbol prefix "12"))
        (%m20 (make-accessor-symbol prefix "20"))
        (%m21 (make-accessor-symbol prefix "21"))
        (%m22 (make-accessor-symbol prefix "22")))
    `(let ((,%m00 ,m00) (,%m01 ,m01) (,%m02 ,m02)
           (,%m10 ,m10) (,%m11 ,m11) (,%m12 ,m12)
           (,%m20 ,m20) (,%m21 ,m21) (,%m22 ,m22))
       (declare (ignorable ,%m00 ,%m01 ,%m02 ,%m10 ,%m11 ,%m12 ,%m20 ,%m21
                           ,%m22))
       ,(if rest
            `(with-elements ,rest ,@body)
            `(progn ,@body)))))
