(defpackage #:gamebox-math
  (:nicknames #:box.math)
  (:use #:cl
        #:alexandria
        #:defstar)

  ;; vec2
  (:export #:vec2
           #:+v2zero+
           #:v2zero!
           #:v2zero
           #:v2cp!
           #:v2cp
           #:v2clamp!
           #:v2clamp
           #:v2stab!
           #:v2stab
           #:v2->list
           #:list->v2
           #:v2=
           #:v2~
           #:v2+!
           #:v2+
           #:v2-!
           #:v2-
           #:v2had*!
           #:v2had*
           #:v2had/!
           #:v2had/
           #:v2scale!
           #:v2scale
           #:v2dot
           #:v2magsq
           #:v2mag
           #:v2normalize!
           #:v2normalize
           #:v2round!
           #:v2round
           #:v2abs!
           #:v2abs
           #:v2neg!
           #:v2neg
           #:v2angle
           #:v2zerop
           #:v2dir=
           #:v2lerp!
           #:v2lerp
           #:v2<
           #:v2<=
           #:v2>
           #:v2>=
           #:v2min!
           #:v2min
           #:v2max!
           #:v2max)

  ;; vec3
  (:export #:vec3
           #:+v3zero+
           #:v3zero!
           #:v3zero
           #:v3cp!
           #:v3cp
           #:v3clamp!
           #:v3clamp
           #:v3stab!
           #:v3stab
           #:v3->list
           #:list->v3
           #:v3=
           #:v3~
           #:v3+!
           #:v3+
           #:v3-!
           #:v3-
           #:v3had*!
           #:v3had*
           #:v3had/!
           #:v3had/
           #:v3scale!
           #:v3scale
           #:v3dot
           #:v3magsq
           #:v3mag
           #:v3normalize!
           #:v3normalize
           #:v3round!
           #:v3round
           #:v3abs!
           #:v3abs
           #:v3neg!
           #:v3neg
           #:v3cross!
           #:v3cross
           #:v3box
           #:v3angle
           #:v3zerop
           #:v3dir=
           #:v3parallelp
           #:v3lerp!
           #:v3lerp
           #:v3<
           #:v3<=
           #:v3>
           #:v3>=
           #:v3min!
           #:v3min
           #:v3max!
           #:v3max)

  ;; vec4
  (:export #:vec4
           #:+v4zero+
           #:v4zero!
           #:v4zero
           #:v4cp!
           #:v4cp
           #:v4clamp!
           #:v4clamp
           #:v4stab!
           #:v4stab
           #:v4->list
           #:list->v4
           #:v4=
           #:v4~
           #:v4+!
           #:v4+
           #:v4-!
           #:v4-
           #:v4had*!
           #:v4had*
           #:v4had/!
           #:v4had/
           #:v4scale!
           #:v4scale
           #:v4dot
           #:v4magsq
           #:v4mag
           #:v4normalize!
           #:v4normalize
           #:v4round!
           #:v4round
           #:v4abs!
           #:v4abs
           #:v4neg!
           #:v4neg
           #:v4zerop
           #:v4lerp!
           #:v4lerp
           #:v4<
           #:v4<=
           #:v4>
           #:v4>=
           #:v4min!
           #:v4min
           #:v4max!
           #:v4max)

  ;; matrix
  (:export #:mat4
           #:mref
           #:+m4zero+
           #:+m4id+
           #:m4zero!
           #:m4zero
           #:m4id!
           #:m4id
           #:m4=
           #:m4~
           #:m4cp!
           #:m4cp
           #:m4clamp!
           #:m4clamp
           #:m4*!
           #:m4*
           #:m4tr->v3!
           #:m4tr->v3
           #:v3->m4tr!
           #:v3->m4tr
           #:m4tr!
           #:m4tr
           #:m4cprot!
           #:m4cprot
           #:m4rot->v3!
           #:m4rot->v3
           #:v3->m4rot!
           #:v3->m4rot
           #:m4rot!
           #:m4rot
           #:m4scale->v3!
           #:m4scale->v3
           #:v3->m4scale!
           #:v3->m4scale
           #:m4scale!
           #:m4scale
           #:m4*v3!
           #:m4*v3
           #:m4*v4!
           #:m4*v4
           #:m4transpose!
           #:m4transpose
           #:m4orthop
           #:m4orthonormalize!
           #:m4orthonormalize
           #:m4trace
           #:m4det
           #:m4invtortho!
           #:m4invtortho
           #:m4invt!
           #:m4invt
           #:m4view!
           #:m4view
           #:m4ortho!
           #:m4ortho
           #:m4persp!
           #:m4persp)

  ;; quaternion
  (:export #:quat
           #:qw
           #:qx
           #:qy
           #:qz
           #:+qzero+
           #:+qid+
           #:qid!
           #:qid
           #:qzero!
           #:qzero
           #:q=
           #:q~
           #:qcp!
           #:qcp
           #:q+!
           #:q+
           #:q-!
           #:q-
           #:q*!
           #:q*
           #:qscale!
           #:qscale
           #:qconj!
           #:qconj
           #:qcross!
           #:qcross
           #:qmagsq
           #:qmag
           #:qnormalize!
           #:qnormalize
           #:qneg!
           #:qneg
           #:qdot
           #:qinv!
           #:qinv
           #:qrot!
           #:qrot
           #:q->v3!
           #:q->v3
           #:q->v4!
           #:q->v4
           #:v3->q!
           #:v3->q
           #:v4->q!
           #:v4->q
           #:q->m4!
           #:q->m4
           #:m4->q!
           #:m4->q
           #:qslerp!
           #:qslerp)

  ;; dual quaternion
  (:export #:dquat
           #:dqid!
           #:dqid
           #:dqzero!
           #:dqzero
           #:dq=
           #:dq~
           #:dqcp!
           #:dqcp
           #:dq+!
           #:dq+
           #:dq-!
           #:dq-
           #:dq*!
           #:dq*
           #:dqscale!
           #:dqscale
           #:dqconj!
           #:dqconj
           #:dqconjf!
           #:dqconjf
           #:dqmagsq
           #:dqmag
           #:dqnormalize!
           #:dqnormalize
           #:dqapply!
           #:dqapply
           #:dqneg!
           #:dqneg
           #:dqdot
           #:dqinv!
           #:dqinv
           #:dqtr->v3!
           #:dqtr->v3
           #:v3->dqtr!
           #:v3->dqtr
           #:dqtr!
           #:dqtr
           #:dqrot->q!
           #:dqrot->q
           #:q->dqrot!
           #:q->dqrot
           #:dqrot!
           #:dqrot
           #:dq->m4!
           #:dq->m4
           #:m4->dq!
           #:m4->dq
           #:dq->screw
           #:screw->dq!
           #:screw->dq
           #:dqsclerp!
           #:dqsclerp
           #:dqnlerp!
           #:dqnlerp))
